### PR TITLE
Upgrade to Python3; switch to Boto3

### PR DESCRIPTION
**Pull request by dllopis-sfdc**
## What does this PR do?
* Makes repo Python 3 compatible.
* Switches from using Boto to Boto3.
* Switches from `requirements.txt` to `Pipfile[.lock]`.

## Why is this change being made?
[W-6902108](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000077ttzIAA/view) _Upgrade repo python-krux-boto-elb to Python 3_

## How does this PR do it?
Modeled Boto3 changes after `krux/python-krux-boto-ec2/krux_ec2/ec2.py`.

## How was this tested? How can the reviewer verify your testing?
Tested the CLI and the `elb.ELB` methods by hand.

## Completion checklist
- [x] The pull request has been appropriately labeled according to
  our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review).
- [x] The version of the package has been updated according to [Semantic Versioning](http://semver.org/).
- [x] The change has unit & integration tests as appropriate.
- [x] Documentation is up to date and correct.
- [x] Dependencies are correctly listed under `Pipfile` and
      are up to date without going over a major version.
- [x] Stakeholders have been notified. Workflow-impacting changes have
      been appropriately socialized to avoid surprises.
- [x] The change is either small or have been canaried in the appropriate environment(s).

### CODE REVIEW

**Comment by instantlinux** [comment]
Has this been tested with VPC target groups? We are no longer using EC2 Classic ELBs.

**Review by dcrampton-sfdc — APPROVED** [review]
Looks sane to me.

**Comment by dllopis-sfdc** [comment]
> Has this been tested with VPC target groups? We are no longer using EC2 Classic ELBs.

This repo isn’t to be used in VPC because Terraform.

**Comment by instantlinux** [comment]
Ok you could merge it—but my comment still stands. This repo is obsolete because we are not using classic ELBs anymore. Go ahead and archive it, and disable the elb functionality in its caller(s) such as manage-instance.

My $.02.

**Comment by dllopis-sfdc** [comment]
> Ok you could merge it—but my comment still stands. This repo is obsolete because we are not using classic ELBs anymore. Go ahead and archive it, and disable the elb functionality in its caller(s) such as manage-instance.
> 
> My $.02.

Fair enough—thanks.

**Pull request merged**
