### PR TITLE
Move `[dev-]requirements.pip` to `[dev-]requirements.txt`.

### PR DESCRIPTION
**Pull request by dllopis-sfdc**
[W-6530307](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000070ucqIAA/view) _Make Python repos support GitHub library dependency scans_

### CODE REVIEW

**Comment by paul-krohn** [comment]
I think you need to update the version of kruxstatsd to get this to build.

**Comment by dllopis-sfdc** [comment]
retest this please

**Comment by dllopis-sfdc** [comment]
retest this please

**Comment by dllopis-sfdc** [comment]
retest this please

**Review by hanpeter — APPROVED** [review]

**Review by dpricha89 — APPROVED** [review]

**Pull request merged**
